#!/usr/bin/env bash

TMUX_ENV=g2x

tmux has-session -t "${TMUX_ENV}"
if [ $? != 0 ]; then
    tmux new-session -s "${TMUX_ENV}" -n camera -d
    tmux send-keys -t "${TMUX_ENV}:0.0" './camera.py' C-m

    tmux new-window -n "pwm" -t "${TMUX_ENV}"
    tmux send-keys -t "${TMUX_ENV}:1.0" './pwm.py' C-m

    tmux new-window -n "pressure" -t "${TMUX_ENV}"
    tmux send-keys -t "${TMUX_ENV}:2.0" './pressure.py' C-m

    tmux new-window -n "volts" -t "${TMUX_ENV}"
    tmux send-keys -t "${TMUX_ENV}:3.0" './voltage.py' C-m

    tmux new-window -n "sense" -t "${TMUX_ENV}"
    tmux send-keys -t "${TMUX_ENV}:4.0" './sense.py' C-m

    tmux new-window -n "bash" -t "${TMUX_ENV}"

    tmux select-window -t "${TMUX_ENV}:0"
fi

tmux attach -t "${TMUX_ENV}"
